{% set name = "cmdstan" %}
{% set version = "2.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
  sha256: 8a34e942ca4c4beee79c61a4258cf18d9757564afadd2f1844df3a3c7f61c801  # [x86 or arm64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 5b1cb5ca120af1dc9d4c1a4bdd7e0899fc409840d3f0083e747c856123940960  # [aarch64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64el.tar.gz  # [ppc64le]
  sha256: 681b1e5d909bfbd691014fb9468a286447b257ee3e0717f4fe07509c96e7dd6b  # [ppc64le]
  patches:
    - no-dtag-flag.patch  # [osx]

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
  host:
    - tbb-devel                    # [not win]
  run:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - tbb-devel                    # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
    - gxx_{{ target_platform }} >={{ cxx_compiler_version }}  # [linux]
  run_constrained:
    - tbb >=2021                   # [win]

test:
  downstreams:
    - cmdstanpy

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
