{% set name = "cmdstan" %}
{% set version = "2.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
  sha256: 770dadcf71a34ec8d94de0836e8d0508d4daa7b7f9380f1563e500945e2b6778  # [x86 or arm64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 0ac742d1bfd094cd48cd471cbb5190e0ac62e0a5862614be22ac40ac1a2a4dee  # [aarch64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64el.tar.gz  # [ppc64le]
  sha256: 9b4d01113659561e9e97bad8fe3a1c8e4dcbb85efce844087574625527541376  # [ppc64le]
  patches:
    - no-dtag-flag.patch  # [osx]

build:
  number: 2
  binary_relocation: false

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - clang                        # [win]
  host:
    - tbb-devel
    - eigen ==3.4.0
    - sundials ==6.1.1
    - boost-cpp ==1.78.0
  run:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - tbb-devel
    - eigen ==3.4.0
    - sundials ==6.1.1
    - boost-cpp ==1.78.0
    - clang                        # [win]

# test:
#   downstreams:
#     - cmdstanpy

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
